name = "fgof-termios"
version = "0.1.0"
license = "MIT"
author = "FortranGoingOnForty"
maintainer = "FortranGoingOnForty"
copyright = "2026"
description = "Terminal mode helpers for modern Fortran tools"

[build]
auto-executables = false
auto-tests = true
auto-examples = false

[install]
library = true

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
